# Generated by Django 3.1.4 on 2021-02-18 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("characterBuilder", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="character",
            old_name="charactername",
            new_name="characterName",
        ),
        migrations.AddField(
            model_name="character",
            name="characterSkills",
            field=models.ManyToManyField(
                related_name="_character_characterSkills_+",
                to="characterBuilder.Character",
            ),
        ),
    ]
