# Generated by Django 3.1.4 on 2021-02-22 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('characterBuilder', '0003_auto_20210217_1859'),
    ]

    operations = [
        migrations.CreateModel(
            name='CharacterTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=240)),
            ],
        ),
        migrations.CreateModel(
            name='CharacterTestChoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.CharField(max_length=240)),
                ('character_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='characterBuilder.charactertest')),
            ],
        ),
    ]
