# Generated by Django 3.1.4 on 2021-02-22 21:39

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("characterBuilder", "0004_charactertest_charactertestchoice"),
    ]

    operations = [
        migrations.RenameField(
            model_name="character",
            old_name="characterDescription",
            new_name="description",
        ),
        migrations.RenameField(
            model_name="character",
            old_name="characterType",
            new_name="kind",
        ),
        migrations.RenameField(
            model_name="character",
            old_name="characterName",
            new_name="name",
        ),
        migrations.RemoveField(
            model_name="character",
            name="char_id",
        ),
        migrations.RemoveField(
            model_name="character",
            name="characterSkills",
        ),
        migrations.AlterField(
            model_name="character",
            name="pub_date",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="date created"
            ),
        ),
        migrations.CreateModel(
            name="Skill",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("level", models.IntegerField()),
                (
                    "character",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="skills",
                        to="characterBuilder.character",
                    ),
                ),
            ],
        ),
    ]
