# Generated by Django 3.1.4 on 2021-03-24 17:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mapBuilder", "0003_auto_20210324_1751"),
        ("characterBuilder", "0009_auto_20210311_1832"),
    ]

    operations = [
        migrations.AddField(
            model_name="character",
            name="dead",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="character",
            name="deathnote",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="visit",
            name="died_here",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="character",
            name="room",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="occupants",
                to="mapBuilder.room",
            ),
        ),
        migrations.CreateModel(
            name="NonPlayerCharacter",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("mobile", models.BooleanField(default=True)),
                ("deadly", models.BooleanField(default=True)),
                ("mortal", models.BooleanField(default=True)),
                (
                    "movement_entropy",
                    models.IntegerField(default=0, help_text="See Movement Threshold"),
                ),
                (
                    "movement_threshold",
                    models.IntegerField(
                        default=100,
                        help_text="When Movement Entropy exceeds this threshold the NPC will move",
                    ),
                ),
                ("warning_text", models.CharField(max_length=200)),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="npcs",
                        to="mapBuilder.room",
                    ),
                ),
            ],
        ),
    ]
