# Generated by Django 3.1.4 on 2021-04-07 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characterBuilder', '0010_auto_20210324_1751'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='character',
        ),
        migrations.AddField(
            model_name='character',
            name='items',
            field=models.ManyToManyField(to='characterBuilder.Item'),
        ),
        migrations.AddField(
            model_name='item',
            name='persistent',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='nonplayercharacter',
            name='loot',
            field=models.ManyToManyField(to='characterBuilder.Item'),
        ),
    ]
