# Generated by Django 3.1.4 on 2021-11-27 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characterBuilder', '0012_auto_20210407_1908'),
    ]

    operations = [
        migrations.AddField(
            model_name='nonplayercharacter',
            name='satanic',
            field=models.BooleanField(default=False),
        ),
    ]
