# Generated by Django 3.1.4 on 2021-11-27 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('characterBuilder', '0013_nonplayercharacter_satanic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nonplayercharacter',
            old_name='satanic',
            new_name='demonic',
        ),
    ]
