# Generated by Django 3.1.4 on 2021-12-11 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('characterBuilder', '0014_auto_20211127_2336'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='items',
        ),
        migrations.RemoveField(
            model_name='nonplayercharacter',
            name='loot',
        ),
        migrations.DeleteModel(
            name='Item',
        ),
    ]
