# Generated by Django 3.1.4 on 2021-12-11 23:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mapBuilder', '0008_auto_20211127_2328'),
        ('characterBuilder', '0015_auto_20211211_2216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nonplayercharacter',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='npcs', to='mapBuilder.room'),
        ),
    ]
