# Generated by Django 3.1.4 on 2022-01-14 23:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('characterBuilder', '0017_remove_character_arrow_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='character',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chosen_one', to='characterBuilder.character'),
        ),
        migrations.AlterField(
            model_name='character',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='characters', to=settings.AUTH_USER_MODEL),
        ),
    ]
