# Generated by Django 3.1.4 on 2022-01-28 01:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mapBuilder', '0010_roomevent'),
        ('characterBuilder', '0018_auto_20220114_2305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='_visits', to='mapBuilder.room'),
        ),
    ]
