# Generated by Django 3.1.4 on 2022-02-12 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characterBuilder', '0019_auto_20220128_0114'),
    ]

    operations = [
        migrations.AddField(
            model_name='nonplayercharacter',
            name='greeting',
            field=models.CharField(blank=True, max_length=140, null=True),
        ),
    ]
