# Generated by Django 3.1.4 on 2021-01-31 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('url', models.URLField()),
                ('exits', models.URLField()),
                ('pub_date', models.DateTimeField(verbose_name='date created')),
                ('description', models.CharField(max_length=600)),
            ],
            options={
                'unique_together': {('id', 'url')},
            },
        ),
    ]
