# Generated by Django 3.1.4 on 2021-02-01 00:08

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapBuilder', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='colorHex',
            field=colorfield.fields.ColorField(default='#222222', max_length=18),
        ),
        migrations.AddField(
            model_name='room',
            name='colorName',
            field=models.CharField(default=222222, max_length=200),
            preserve_default=False,
        ),
    ]
