# Generated by Django 3.1.4 on 2021-02-02 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapBuilder', '0002_auto_20210131_1608'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='status',
            field=models.CharField(default='null', max_length=200),
            preserve_default=False,
        ),
    ]
