# Generated by Django 3.1.4 on 2021-02-06 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapBuilder', '0003_room_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='exits',
        ),
        migrations.AddField(
            model_name='room',
            name='exits',
            field=models.ManyToManyField(related_name='_room_exits_+', to='mapBuilder.Room'),
        ),
    ]
