# Generated by Django 3.1.4 on 2021-02-10 18:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mapBuilder', '0004_auto_20210206_1417'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='colorSlug',
            field=models.SlugField(null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='pub_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
