# Generated by Django 3.1.4 on 2021-02-12 18:47

import colorfield.fields
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Room",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("url", models.URLField()),
                (
                    "pub_date",
                    models.DateTimeField(blank=True, default=django.utils.timezone.now),
                ),
                ("description", models.CharField(max_length=600)),
                ("colorName", models.CharField(max_length=200)),
                ("status", models.CharField(max_length=200)),
                (
                    "colorHex",
                    colorfield.fields.ColorField(default="#222222", max_length=18),
                ),
                ("colorSlug", models.SlugField(null=True)),
                (
                    "exits",
                    models.ManyToManyField(
                        related_name="_room_exits_+", to="mapBuilder.Room"
                    ),
                ),
            ],
            options={
                "unique_together": {("id", "url")},
            },
        ),
    ]
