# Generated by Django 3.1.4 on 2021-03-24 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapBuilder', '0002_room_arrow_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='room',
            name='status',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='room',
            name='url',
            field=models.URLField(blank=True),
        ),
    ]
