# Generated by Django 3.1.4 on 2021-11-21 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapBuilder', '0004_auto_20210407_1934'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='illumination_level',
            field=models.IntegerField(default=0),
        ),
    ]
