# Generated by Django 3.1.4 on 2021-11-21 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mapBuilder', '0005_room_illumination_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='illumination_level',
        ),
    ]
