# Generated by Django 3.1.4 on 2021-11-27 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapBuilder', '0006_remove_room_illumination_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='cleanliness',
            field=models.IntegerField(default=0),
        ),
    ]
