# Generated by Django 3.1.4 on 2021-11-27 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapBuilder', '0007_room_cleanliness'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='is_cursed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='room',
            name='cleanliness',
            field=models.IntegerField(default=1),
        ),
    ]
