# Generated by Django 3.1.4 on 2022-01-08 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mapBuilder', '0008_auto_20211127_2328'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='arrow_count',
        ),
    ]
