# Generated by Django 3.1.4 on 2022-01-28 01:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mapBuilder', '0009_remove_room_arrow_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('text', models.CharField(max_length=256)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='mapBuilder.room')),
            ],
        ),
    ]
