# Generated by Django 3.1.4 on 2022-01-29 21:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mapBuilder', '0010_roomevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cenotaph',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('name', models.CharField(max_length=64)),
                ('birth', models.DateTimeField()),
                ('death', models.DateTimeField()),
                ('room', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='cenotaph', to='mapBuilder.room')),
            ],
        ),
    ]
