# Generated by Django 3.1.4 on 2022-01-29 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapBuilder', '0011_cenotaph'),
    ]

    operations = [
        migrations.AddField(
            model_name='cenotaph',
            name='portrait_filename',
            field=models.CharField(default='images/portraits/rodney.png', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cenotaph',
            name='scene',
            field=models.TextField(default='', help_text="This 'a-frame' will be inserted in the cenotaph as background"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cenotaph',
            name='birth',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='cenotaph',
            name='death',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='cenotaph',
            name='text',
            field=models.TextField(help_text='The inscription on the cenotaph'),
        ),
    ]
