# Generated by Django 3.1.4 on 2022-01-29 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapBuilder', '0012_auto_20220129_2330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cenotaph',
            name='birth',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='cenotaph',
            name='death',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='cenotaph',
            name='portrait_filename',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='cenotaph',
            name='scene',
            field=models.TextField(blank=True, help_text="This 'a-frame' will be inserted in the cenotaph as background", null=True),
        ),
    ]
