# Generated by Django 3.1.4 on 2022-02-11 22:23

from django.db import migrations, models
import django.db.models.deletion
import mapBuilder.models
import mapBuilder.validators


class Migration(migrations.Migration):

    dependencies = [
        ('mapBuilder', '0013_auto_20220129_2331'),
    ]

    operations = [
        migrations.CreateModel(
            name='CenotaphFileUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=mapBuilder.models.centaph_file_uploads, validators=[mapBuilder.validators.validate_pdf_image_or_audio])),
                ('original_filename', models.CharField(max_length=128)),
                ('extension', models.CharField(max_length=8)),
                ('cenotaph', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='mapBuilder.cenotaph')),
            ],
        ),
    ]
