# Generated by Django 3.1.4 on 2022-02-11 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mapBuilder', '0014_cenotaphfileupload'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CenotaphFileUpload',
            new_name='CenotaphFile',
        ),
    ]
