# Generated by Django 3.1.4 on 2022-02-11 23:02

from django.db import migrations, models
import mapBuilder.models
import mapBuilder.validators


class Migration(migrations.Migration):

    dependencies = [
        ('mapBuilder', '0015_auto_20220211_1425'),
    ]

    operations = [
        migrations.AddField(
            model_name='cenotaph',
            name='portrait',
            field=models.FileField(null=True, upload_to=mapBuilder.models.centaph_portrait_uploads, validators=[mapBuilder.validators.validate_pdf_image_or_audio]),
        ),
        migrations.AlterField(
            model_name='cenotaph',
            name='portrait_filename',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='cenotaphfile',
            name='extension',
            field=models.CharField(blank=True, max_length=8),
        ),
        migrations.AlterField(
            model_name='cenotaphfile',
            name='original_filename',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
