# Generated by Django 3.1.4 on 2021-01-31 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characterBuilder', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='characterType',
            field=models.CharField(default=2, max_length=200),
            preserve_default=False,
        ),
    ]
