# Generated by Django 3.1.4 on 2021-02-18 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characterBuilder', '0002_auto_20210217_1844'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='characterSkills',
        ),
        migrations.AddField(
            model_name='character',
            name='characterSkills',
            field=models.CharField(default='poopiness: 1', max_length=200),
            preserve_default=False,
        ),
    ]
