# Generated by Django 3.1.4 on 2021-02-12 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('characterBuilder', '0002_character_charactertype'),
    ]

    operations = [
        migrations.RenameField(
            model_name='character',
            old_name='description',
            new_name='characterDescription',
        ),
        migrations.RenameField(
            model_name='character',
            old_name='name',
            new_name='charactername',
        ),
    ]
