# Generated by Django 3.1.4 on 2021-02-23 19:12

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mapBuilder', '0001_initial'),
        ('characterBuilder', '0005_auto_20210222_2139'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mapBuilder.room'),
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stamp_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date created')),
                ('character', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='characterBuilder.character')),
                ('room', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mapBuilder.room')),
            ],
        ),
    ]
