name: Docker Push

on:
  push:
    branches:
    - main

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - name: Docker Build & Push to Docker Hub
        uses: opspresso/action-docker@master
        with:
          args: --docker
        env:
          USERNAME: ${{ secrets.DOCKER_USERNAME }}
          PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          DOCKERFILE: "Dockerfile"
          IMAGE_NAME: "thismatters/grotto"
          TAG_NAME: "v0.0.1"
          LATEST: "true"

      - name: Deploy to Prod
        uses: garygrossgarten/github-action-ssh@release
        with:
          command: cd prod && docker pull thismatters/grotto:latest && docker-compose up -d
          host: ${{ secrets.HOST }}
          username: grotto
          privateKey: ${{ secrets.PROD_SSH_KEY }}
