# Generated by Django 3.1.4 on 2021-11-21 20:44

import colorfield.fields
from django.db import migrations, models
import django.db.models.deletion
import django_enumfield.db.fields
import itemBuilder.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mapBuilder', '0006_remove_room_illumination_level'),
        ('characterBuilder', '0012_auto_20210407_1908'),
    ]

    operations = [
        migrations.CreateModel(
            name='AbstractItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemType', django_enumfield.db.fields.EnumField(enum=itemBuilder.models.ItemType)),
                ('itemName', models.CharField(max_length=64)),
                ('itemDescription', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.DateTimeField(blank=True, null=True)),
                ('colorName', models.CharField(max_length=200)),
                ('colorHex', colorfield.fields.ColorField(default='#222222', max_length=18)),
                ('abstract_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='itemBuilder.abstractitem')),
                ('current_owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='characterBuilder.character')),
                ('current_room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='room_items', to='mapBuilder.room')),
            ],
        ),
    ]
