# Generated by Django 3.1.4 on 2021-11-27 22:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('characterBuilder', '0012_auto_20210407_1908'),
        ('mapBuilder', '0006_remove_room_illumination_level'),
        ('itemBuilder', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='abstractitem',
            name='active_days',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='current_owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='character_items', to='characterBuilder.character'),
        ),
        migrations.AlterField(
            model_name='item',
            name='current_room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='mapBuilder.room'),
        ),
    ]
