# Generated by Django 3.1.4 on 2021-12-11 22:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('characterBuilder', '0015_auto_20211211_2216'),
        ('itemBuilder', '0002_auto_20211127_2232'),
    ]

    operations = [
        migrations.AddField(
            model_name='abstractitem',
            name='holders',
            field=models.ManyToManyField(related_name='loot', to='characterBuilder.NonPlayerCharacter'),
        ),
        migrations.AddField(
            model_name='abstractitem',
            name='untakable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='abstractitem',
            name='untakable_if_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='item',
            name='current_owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory', to='characterBuilder.character'),
        ),
    ]
