# Generated by Django 3.1.4 on 2021-12-11 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemBuilder', '0003_auto_20211211_2216'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='description',
            field=models.CharField(default='blank', max_length=256),
        ),
        migrations.AddField(
            model_name='item',
            name='name',
            field=models.CharField(default='blank', max_length=128),
        ),
    ]
