# Generated by Django 3.1.4 on 2021-12-11 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characterBuilder', '0016_auto_20211211_2323'),
        ('itemBuilder', '0004_auto_20211211_2245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abstractitem',
            name='holders',
            field=models.ManyToManyField(blank=True, related_name='loot', to='characterBuilder.NonPlayerCharacter'),
        ),
    ]
