# Generated by Django 3.1.4 on 2022-01-08 19:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('characterBuilder', '0017_remove_character_arrow_count'),
        ('itemBuilder', '0005_auto_20211211_2323'),
    ]

    operations = [
        migrations.CreateModel(
            name='Swap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=200)),
                ('npc', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='characterBuilder.nonplayercharacter')),
                ('picks', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='wanted', to='itemBuilder.abstractitem')),
                ('puts', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='itemBuilder.abstractitem')),
            ],
        ),
    ]
