# Generated by Django 3.1.4 on 2022-01-15 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemBuilder', '0007_abstractitem_viewable'),
    ]

    operations = [
        migrations.AddField(
            model_name='abstractitem',
            name='usable',
            field=models.BooleanField(default=False),
        ),
    ]
