# Generated by Django 3.1.4 on 2022-01-15 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemBuilder', '0008_abstractitem_usable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='abstractitem',
            name='active_days',
        ),
        migrations.AddField(
            model_name='abstractitem',
            name='active_time',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
