# Generated by Django 3.1.4 on 2022-01-15 23:50

from django.db import migrations
import django_enumfield.db.fields
import itemBuilder.enum


class Migration(migrations.Migration):

    dependencies = [
        ('itemBuilder', '0009_auto_20220115_2329'),
    ]

    operations = [
        migrations.AddField(
            model_name='swap',
            name='picks_type',
            field=django_enumfield.db.fields.EnumField(default=1, enum=itemBuilder.enum.ItemType),
            preserve_default=False,
        ),
    ]
