# Generated by Django 3.1.4 on 2022-01-15 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itemBuilder', '0010_swap_picks_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='swap',
            name='picks',
        ),
    ]
